local T, C, L = unpack(Tukui)

if not C.chat.enable == true then return end

ChatFrame4Tab:Kill()
ChatFrame4:Kill()
ChatFrame_RemoveAllMessageGroups(ChatFrame4)
ChatFrame_AddMessageGroup(ChatFrame3, "COMBAT_XP_GAIN")
ChatFrame_AddMessageGroup(ChatFrame3, "COMBAT_HONOR_GAIN")
ChatFrame_AddMessageGroup(ChatFrame3, "COMBAT_FACTION_CHANGE")
ChatFrame_AddMessageGroup(ChatFrame3, "LOOT")
ChatFrame_AddMessageGroup(ChatFrame3, "MONEY")
ChatFrame_AddMessageGroup(ChatFrame3, "SAY")
ChatFrame_AddMessageGroup(ChatFrame3, "EMOTE")
ChatFrame_AddMessageGroup(ChatFrame3, "YELL")
ChatFrame_AddMessageGroup(ChatFrame3, "GUILD")
ChatFrame_AddMessageGroup(ChatFrame3, "OFFICER")
ChatFrame_AddMessageGroup(ChatFrame3, "GUILD_ACHIEVEMENT")
ChatFrame_AddMessageGroup(ChatFrame3, "WHISPER")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_SAY")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_EMOTE")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_YELL")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_WHISPER")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_BOSS_EMOTE")
ChatFrame_AddMessageGroup(ChatFrame3, "MONSTER_BOSS_WHISPER")
ChatFrame_AddMessageGroup(ChatFrame3, "PARTY")
ChatFrame_AddMessageGroup(ChatFrame3, "PARTY_LEADER")
ChatFrame_AddMessageGroup(ChatFrame3, "RAID")
ChatFrame_AddMessageGroup(ChatFrame3, "RAID_LEADER")
ChatFrame_AddMessageGroup(ChatFrame3, "RAID_WARNING")
ChatFrame_AddMessageGroup(ChatFrame3, "BATTLEGROUND")
ChatFrame_AddMessageGroup(ChatFrame3, "BATTLEGROUND_LEADER")
ChatFrame_AddMessageGroup(ChatFrame3, "BG_HORDE")
ChatFrame_AddMessageGroup(ChatFrame3, "BG_ALLIANCE")
ChatFrame_AddMessageGroup(ChatFrame3, "BG_NEUTRAL")
ChatFrame_AddMessageGroup(ChatFrame3, "SYSTEM")
ChatFrame_AddMessageGroup(ChatFrame3, "ERRORS")
ChatFrame_AddMessageGroup(ChatFrame3, "AFK")
ChatFrame_AddMessageGroup(ChatFrame3, "DND")
ChatFrame_AddMessageGroup(ChatFrame3, "IGNORED")
ChatFrame_AddMessageGroup(ChatFrame3, "ACHIEVEMENT")
ChatFrame_AddMessageGroup(ChatFrame3, "BN_WHISPER")
ChatFrame_AddMessageGroup(ChatFrame3, "BN_CONVERSATION")